import type { Metadata } from "next";
import "./globals.css";
import Head from "@/components/ui/Head";
import MyProviders from "@/components/theme-Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`ease-linear `}>
        <MyProviders>
          <div className="w-full h-full absolute left-0 top-0 dark:bg-black bg-white">
            <div className="w-full h-[60px] absolute left-0 top-0">
              <Head />
            </div>
            <div className="w-full h-[calc(100%-60px] top-[60px] absolute">
              {children}
            </div>
          </div>
        </MyProviders>
      </body>
    </html>
  );
}
