import type { Metadata } from "next";
import "./globals.css";
import Head from "@/components/ui/Head";
import MyProviders from "@/components/theme-Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`ease-linear `}>
        <MyProviders>
          <div className="w-full h-full overflow-auto absolute left-0 top-0 dark:bg-black bg-gray-100 p-8">
            <div className="w-full h-[60px] top-0 left-0 px-8 absolute">
              <Head />
            </div>
            <div className="w-full relative mt-[60px]">{children}</div>
          </div>
        </MyProviders>
      </body>
    </html>
  );
}
